### ISSUE TITLE
Will the next release support the new STRICT and STANDARD setting categories?

### ISSUE THREAD

**Issue by stuartschifter-AMA** [cammurray/orca#10]
Will the next release support the new STRICT and STANDARD setting categories?
See https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/recommended-settings-for-eop-and-office365-atp

**Comment by cammurray** [comment]
Hi @stuartschifter-AMA 

Definitely! This is currently on our backlog. I can't specifically say the exact release that'll have it but i'm hoping within the next month.

**Comment by stuartschifter-AMA** [comment]
Cam, could you share this feedback with the team leading the STANDARD \ STRICT policy direction?

We like many enterprises will adhere with the STRICT baseline which recommends a dependency on the Office 365 Quarantine.   STRICT will require visiting the URL https://protection.office.com/quarantine    Moving forward to improve the User Experience, Outlook should have a "Quarantine" Toolbar button or a Right Click action that launches a browser window to the destination.   In the past I would have recommended creating a Folder in the Mailbox with the Home Folder set to the link.  But, that feature has been depreciated as a Threat Vector and is no longer enabled.

**Comment by DavidTaig** [comment]
Yes please, as I am getting **Improvement** when I have these set with Strict setting
Outbound spam filter policy settings
Bulk Action

Happy to test out the Beta of 1.5 for you

**Comment by cammurray** [comment]
Thanks @DavidTaig - we will be pushing out an interim 1.5 before this, and hope to do 2.0 next month.  I'm trying to get nightly builds to go in to GitHub for testing before I send them to PS Gallery.

**Comment by DavidTaig** [comment]
>  I'm trying to get nightly builds to go in to GitHub for testing before I send them to PS Gallery.

@cammurray have you uploaded any builds

**Comment by cammurray** [comment]
Code for strict has been checked in.

Control will pass if the setting is either at strict or standard, showing next to the pass it's current setting.. see below:

![image](https://user-images.githubusercontent.com/26195772/78517479-ce052c00-7800-11ea-8fcd-6819df644bd3.png)

Going through final checks but this is on schedule for next couple of days

@DavidTaig @stuartschifter-AMA
