### ISSUE TITLE
Output File name and directory

### ISSUE THREAD

**Issue by decturau** [cammurray/orca#106]
Cannot ouput the file to a custom directory or file name. Tried:
- OutputFile
- OutputDirectory
-ReportFileName
-Report

All of which save it in app data with the scripted name format. How do achieve custom directory/name? 

Thanks.

**Comment by cammurray** [comment]
If you want in a different directory, it's a little more complicated, you'll need to tell the HTML output module to put it somewhere;

Example:

Invoke-ORCA -Output HTML -OutputOptions @{HTML=@{OutputDirectory="c:\reports\"}}

**Comment by cammurray** [comment]
Closing as no responses.
