### ISSUE TITLE
No output file...

### ISSUE THREAD

**Issue by b-kinsman** [cammurray/orca#108]
I have updated orca, verified permissions, attempted changing directory before running Get-ORCAReport but not matter what I do I don't get an output file.. 

final output is always..

08/13/2020 11:17:06 Complete! Output is in

Any suggestions?
(I am on Mac in a Windows VM, could it be a vm/host permission issue maybe?)

**Comment by cammurray** [comment]
Hi @b-kinsman - interesting, are you just running Get-ORCAReport by itself? What version of windows are you running in the VM?

**Comment by b-kinsman** [comment]
Hi @cammurray yep. tried with Get-ORCAReport, Invoke-ORCA -Output HTML & setup another Windows VM to test (with shared desktop, etc disabled), issue appears to be persistent..
System is Win 10Pro v.1909 OS Build 18363.1016 in VMWare Fusion Pro V11.5.6 (16696540)

**Comment by cammurray** [comment]
@b-kinsman do you have the full output log for me? I suspect that this has something to do with not being able to determine the appdata path and/or create a directory,

Can you also try this for me, make a directory c:\temp\reports or something and then try tell the output to go there?

Invoke-ORCA -Output HTML -OutputOptions @{HTML=@{OutputDirectory="c:\temp\reports\"}}

**Comment by b-kinsman** [comment]
ah I had the output option wrong in my test..but just tried using the above method: no output file...

**Comment by NehavPandey** [comment]
Fix released in 1.10.6.
