### ISSUE TITLE
orca script does not recognize EOP .us endpoints as EOP

### ISSUE THREAD

**Issue by GTH20** [cammurray/orca#109]
Update orca script to recognize domain.mail.protection.office365.**us** as EOP. 

It appears the orca script only recognizes domain.mail.protection.outlook.**com** as EOP at this time.

**Comment by cammurray** [comment]
@GTH20 where are you seeing this fail because of the .us endpoints? I don't believe we are doing any matching of the mail-entry point.

**Comment by cammurray** [comment]
Closing off as no response from author @GTH20 if still an issue. Feel free to re-open if still a problem.
