### ISSUE TITLE
[Request] Publish code in repo to allow pull requests

### ISSUE THREAD

**Issue by f-bader** [cammurray/orca#11]
Hi @cammurray, 

thanks for the great tool. Have you considered to also publish the actual code in the repo to allow the community to make pull requests.
I understand that there may be licensing issues that would prevent this, but it would make it so much easier to propose changes / features

All the best, Fabian

**Comment by cammurray** [comment]
Hey @f-bader 

There's no licensing constraints. The only reason as to why it's not up here at the moment is the work started within azure devops, so the repo is in there at the moment. Now it's public, we want to move the repo in to github and work off it in here. Won't be long!

**Comment by cammurray** [comment]
Hey @f-bader 

All our code is now checked in to github from DevOps. The code that's checked in is the new 1.4 release which isn't on PSGallery yet.

Closing this now.
