### ISSUE TITLE
Preset Security Policy shows up even when not set or disabled

### ISSUE THREAD

**Issue by abhitalks** [cammurray/orca#114]
**Problem**: The [Preset Security Policies](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/preset-security-policies?view=o365-worldwide) (both Standard and Strict) are shown in the report as "OK" marked with "Standard" or "Strict" tags. 

This is the case even when the policies are not configured (i.e. there are no assignments / applies-to yet). Checking with PowerShell "`Get-xxxRule`" confirms that no rules are in place. PowerShell "`Get-ATPProtectionPolicyRule`" also returns nothing confirming the same. Yet the ORCA report gladly shows the policies/rules in each section in green and adds to the total "OK" count. 

This is also the case when the policies are disabled. 

**Expected Behaviour**: The preset security policies if disabled or not configured should either not be shown in the report, or should show up as informational as in the case of transport rules.

**Version**: 1.9.11

**Steps to reproduce**:

1. Use a tenant where the tile called "Preset Security Policies" under the "Templated Policies" section is never clicked. This means, the preset policies are not created yet.
2. Run ORCA to generate a report.
3. The report will not show the preset policies anywhere.
4. Click on the "Preset Security Policies" tile under the "Templated Policies" section. But do not configure anything and leave the templates/policies in disabled state.
5. Run ORCA to generate a report.
6. The report will show all the preset policies (both standard and strict) with respective green tags and adds to the "OK" score.

Note: Toggling enabled/disabled state does not make any difference. 

Note 2: Once the "Preset Security Policies" tile is clicked, the present policies are created but without rules unless configured.

**Comment by NehavPandey** [comment]
@abhitalks Can you confirm the exact section report where you see this issue?

**Comment by NehavPandey** [comment]
No response received from OP. Closing this issue.  @abhitalks Please reopen if issue persists.
