### ISSUE TITLE
Rights in documentation are not sufficient

### ISSUE THREAD

**Issue by guusverbeek** [cammurray/orca#115]
Hi Community,

the documentation states
`For example you can use the following:

    Global Reader - Azure Active Directory role
    View-Only Organization Management - built in role group in Exchange Online`

However, upon testing with these permissions we get the error
ORCA was unable to connect to Exchange Online, or you do not have sufficient permissions to check ORCA related configuration.

It seems as if these permissions are not sufficient for all gathering all relevant data. Or am I missing something here?

**Comment by cammurray** [comment]
Hi @guusverbeek 

Can you confirm what level permission you have out of those two? Can you then try run:

Connect-ExchangeOnline

Followed by

Get-HostedConnectionFilterPolicy

Do you receive an error?

**Comment by NehavPandey** [comment]
No response received from OP. Closing this issue. Please reopen if issue persists.
