### ISSUE TITLE
Output to Desktop

### ISSUE THREAD

**Issue by gpanucci** [cammurray/orca#118]
Hi, 
I was just looking at the ORCA tool which is excellent, however I'm trying to write a script that will always output to the desktop, using userprofile\Desktop won't work because if people are using OneDrive KFM then the Desktop doesn't exist in that location(I'm guessing it'll be the same for FolderRedirection also), so I've been trying to use: 

`$DesktopPath = [System.Environment]::GetFolderPath([System.Environment+SpecialFolder]::Desktop)`
`Invoke-ORCA -Output HTML -OutputOptions @{HTML=@{OutputDirectory=$DesktopPath}}`

The desktop path gives the correct result but it doesn't seem like the Output Directory will accept it as a location

Can you please see what you can do to get this working, or advise if I'm doing something wrong.

Thanks!

**Comment by cammurray** [comment]
Hi @gpanucci 

Does your Desktop Path by any chance contain spaces? Do you get any errors on the screen? When the module finishes, what is in the "Result" column

**Comment by gpanucci** [comment]
Hi @cammurray ,

Thanks for getting back to me.

Yeah it does have spaces because the OneDrive location is "OneDrive - $CompanyName\Desktop" when you turn on KFM so there are spaces between the OneDrive and the - and then again between the company name.

Please let me know if you need any further info.

The error is:

Invoke-Expression : The term 'D:\OneDrive\OneDrive' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Program Files\WindowsPowerShell\Modules\ORCA\1.9.11\Outputs\output-html.ps1:571 char:13
+             Invoke-Expression $OutputFile
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:\OneDrive\OneDrive:String) [Invoke-Expression], CommandNotFoundExcept
   ion
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by cammurray** [comment]
Hi @gpanucci 

I believe that I know what's causing the invoke-expression error but i'm just trying to determine if there's something bigger at play too. When you get the error, do you also get underneath it a table that looks like this?

Completed Result Name
--------- ------ ----

What do you see in that table?

**Comment by gpanucci** [comment]
Hi @cammurray ,

There is no table, I copied the end of the text after running the invoke.

Let me know.

Thanks!

**Comment by gpanucci** [comment]
Hi @cammurray ,

Just wondering if you ended up with any solution for getting it to write to the desktop?

Let me know.

Thanks!

**Comment by NehavPandey** [comment]
Fix released in 1.10.6.
