### ISSUE TITLE
Module based on ORCA

### ISSUE THREAD

**Issue by mpiederiet** [cammurray/orca#12]
Hi Cam, I've taken the liberty of modifying your module to make it more modular, also adding checks for Intune ATP and Azure ATP. Please have a look at it at https://github.com/mpiederiet/test-atpbaseline and let me know what you think of it? (sorry to use "issues" for this; unfortunately there is no way to do "private messaging" on Github.)

Best regards,
Maarten

**Comment by cammurray** [comment]
Thanks for the fyi Maarten, feel free to port any changes from ORCA to your code as it comes in. We will be checking the main code in to github some stage in the coming weeks.
