### ISSUE TITLE
No Output. Multiple Errors.

### ISSUE THREAD

**Issue by winston15** [cammurray/orca#120]
Hello,

When attempting to run `Get-ORCAReport` I receive the following output:

> PS C:\Temp> Get-ORCAReport
> 11/20/2020 09:29:15 Performing ORCA Version check...
> 11/20/2020 09:29:22 Connecting to Exchange Online (Modern Module)..
> 
> ----------------------------------------------------------------------------
> The module allows access to all existing remote PowerShell (V1) cmdlets in addition to the 9 new, faster, and more reliable cmdlets.
> 
> |--------------------------------------------------------------------------|
> |    Old Cmdlets                    |    New/Reliable/Faster Cmdlets       |
> |--------------------------------------------------------------------------|
> |    Get-CASMailbox                 |    Get-EXOCASMailbox                 |
> |    Get-Mailbox                    |    Get-EXOMailbox                    |
> |    Get-MailboxFolderPermission    |    Get-EXOMailboxFolderPermission    |
> |    Get-MailboxFolderStatistics    |    Get-EXOMailboxFolderStatistics    |
> |    Get-MailboxPermission          |    Get-EXOMailboxPermission          |
> |    Get-MailboxStatistics          |    Get-EXOMailboxStatistics          |
> |    Get-MobileDeviceStatistics     |    Get-EXOMobileDeviceStatistics     |
> |    Get-Recipient                  |    Get-EXORecipient                  |
> |    Get-RecipientPermission        |    Get-EXORecipientPermission        |
> |--------------------------------------------------------------------------|
> 
> To get additional information, run: Get-Help Connect-ExchangeOnline or check https://aka.ms/exops-docs
> 
> Send your product improvement suggestions and feedback to exocmdletpreview@service.microsoft.com. For issues related to the module, contact Microsoft support. Don't use the feedback alias for problems or support issues.
> ----------------------------------------------------------------------------
> 
> New-Object : Cannot find type [html]: verify that the assembly containing this type is loaded.
> At line:32 char:16
> +         return & $origNewObject @psBoundParameters
> +                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
>     + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
> 
> The property 'DefaultOutputDirectory' cannot be found on this object. Verify that the property exists and can be set.
> At C:\Program Files\WindowsPowerShell\Modules\ORCA\1.9.11\ORCA.psm1:410 char:17
> +                 $Output.DefaultOutputDirectory = Get-ORCADirectory
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>     + FullyQualifiedErrorId : PropertyNotFound
> 
> The property 'VersionCheck' cannot be found on this object. Verify that the property exists and can be set.
> At C:\Program Files\WindowsPowerShell\Modules\ORCA\1.9.11\ORCA.psm1:413 char:17
> +                 $Output.VersionCheck = $VersionCheck
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>     + FullyQualifiedErrorId : PropertyNotFound
> 
> New-Object : Cannot find type [ORCA100]: verify that the assembly containing this type is loaded.
> At line:32 char:16
> +         return & $origNewObject @psBoundParameters
> +                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
>     + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
> 
> The property 'ORCAParams' cannot be found on this object. Verify that the property exists and can be set.
> At C:\Program Files\WindowsPowerShell\Modules\ORCA\1.9.11\ORCA.psm1:352 char:13
> +             $Check.ORCAParams = $ORCAParams
> +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>     + FullyQualifiedErrorId : PropertyNotFound`
> 
> The last two errors repeat several times (for ORCA100 -> ORCA234). Then:
> `11/20/2020 09:29:45 Getting Anti-Spam Settings
> 11/20/2020 09:29:47 Getting Tenant Settings
> 11/20/2020 09:29:47 Getting Anti Phish Settings
> 11/20/2020 09:29:48 Getting Anti-Malware Settings
> 11/20/2020 09:29:48 Getting Transport Rules
> 11/20/2020 09:29:49 Getting ATP Policies
> 11/20/2020 09:29:50 Getting Accepted Domains
> 11/20/2020 09:29:51 Getting DKIM Configuration
> 11/20/2020 09:29:51 Getting Connectors
> 11/20/2020 09:29:51 Getting MX Reports for all domains
> 11/20/2020 09:30:59 Generating Output
> 11/20/2020 09:30:59 Complete! Output is in
> PS C:\Temp>

There doesn't appear to be any output.
I also tried this:

> PS C:\reports> Invoke-ORCA -Output HTML -OutputOptions @{HTML=@{OutputDirectory="c:\reports"}}
> 11/20/2020 09:38:39 Performing ORCA Version check...
> New-Object : Cannot find type [html]: verify that the assembly containing this type is loaded.
> At line:32 char:16
> +         return & $origNewObject @psBoundParameters
> +                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
>     + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand
> 
> Get-Member : You must specify an object for the Get-Member cmdlet.
> At C:\Program Files\WindowsPowerShell\Modules\ORCA\1.9.11\ORCA.psm1:395 char:54
> + ...                       $ModProperties = $($Output | Get-Member | Where ...
> +                                                        ~~~~~~~~~~
>     + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
>     + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand
> 
> There is no option OutputDirectory on output module html
> At C:\Program Files\WindowsPowerShell\Modules\ORCA\1.9.11\ORCA.psm1:403 char:29
> + ...             Throw("There is no option $($Opt) on output module $($mat ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (There is no opt...put module html:String) [], RuntimeException
>     + FullyQualifiedErrorId : There is no option OutputDirectory on output module html

Running on Windows 10 with Global Reader credentials in an elevated PowerShell 5.1 window.
Please let me know if you require any additional information. Thank you so much for the work that you've put into this script.

**Comment by DESCHAMPS78** [comment]
Hi,
I have exactly the same issue with simple command : Get-ORCAReport
If anybody has a solution (even changing output type : csv ....) does not solve the issue.
Thanks !

**Comment by DESCHAMPS78** [comment]
Error is : New-Object : Cannot find type [html]: verify that the assembly containing this type is loaded.
At line:32 char:16

**Comment by winston15** [comment]
This ended up being a compatibility issue on my end with SentinalOne ( found in issue #20 ). I spun up a sandbox and ran the script there successfully. Thank you!
