### ISSUE TITLE
Powershell 7 support

### ISSUE THREAD

**Issue by davidcrossland** [cammurray/orca#121]
Probably more of a question, ive noted the ExchangeOnlineManagement module has a preview for Powershell 7.  Im hoping that at some point (and im wondering when) the ORCA module can be updated to work with this? Atm im being forced to use an automation account in azure to execute the report, i would much prefer to be using an Azure Powershell Function as soon as possible.   Ofc ive no idea when ExchangeOnlineManagement will come out of preview..

**Comment by cammurray** [comment]
I think this is outdated, I'm running PowerShell 7.3 with no issue. If you believe there's a concern feel free to comment and re-open.
