### ISSUE TITLE
Unsolveable issue in ORCA Report... false positive?

### ISSUE THREAD

**Issue by luckman212** [cammurray/orca#124]
#### I got these 2 warnings for ATP:

1. Domain Impersonation Action → Configure domain impersonation action to Quarantine → Strict Preset Security Policy → TargetedDomainProtectionAction: **MoveToJmf** (should be: **Quarantine**)

    ![image](https://user-images.githubusercontent.com/1992842/102004622-7d739600-3ce0-11eb-8bae-941ca39ede3c.png)

2. Anti-spoofing protection → Enable anti-spoofing protection in Anti-phishing policy → Antispoof Enforced: **False** (should be: **True**)

    ![image](https://user-images.githubusercontent.com/1992842/102004750-6b462780-3ce1-11eb-8e3f-b26d35b0bbb6.png)

#### Here's the Default policy: (everything already set to enabled/Quarantine)
![image](https://user-images.githubusercontent.com/1992842/102004683-efe47600-3ce0-11eb-9db5-e8036e64083d.png)

#### ...and my 1 custom policy: (also all set to enabled/Quarantine)
![image](https://user-images.githubusercontent.com/1992842/102004697-0e4a7180-3ce1-11eb-8000-1b3dafad8e04.png)

#### **Trying to remediate via PowerShell:** (change is not allowed)
```powershell
PS C:\> Set-AntiPhishPolicy -Id "Strict Preset Security Policy" -TargetedDomainProtectionAction Quarantine
WARNING: All recommended properties will be controlled by Microsoft.
```

#### ...and, nothing in here about `Antispoof Enforced` being off or anything else to be enabled, etc... can't find a refrence to this setting anywhere...?
```powershell
PS C:\> Get-AntiPhishPolicy | fl Id,*able*,*force*

Id                                  : Strict Preset Security Policy
Enabled                             : True
EnableTargetedUserProtection        : True
EnableMailboxIntelligenceProtection : True
EnableTargetedDomainsProtection     : True
EnableOrganizationDomainsProtection : True
EnableMailboxIntelligence           : True
EnableSimilarUsersSafetyTips        : True
EnableSimilarDomainsSafetyTips      : True
EnableUnusualCharactersSafetyTips   : True
EnableSpoofIntelligence             : True
EnableViaTag                        : True
EnableUnauthenticatedSender         : True
EnableSuspiciousSafetyTip           : True

Id                                  : Custom-AntiPhishPolicy
Enabled                             : True
EnableTargetedUserProtection        : True
EnableMailboxIntelligenceProtection : True
EnableTargetedDomainsProtection     : True
EnableOrganizationDomainsProtection : True
EnableMailboxIntelligence           : True
EnableSimilarUsersSafetyTips        : True
EnableSimilarDomainsSafetyTips      : True
EnableUnusualCharactersSafetyTips   : True
EnableSpoofIntelligence             : True
EnableViaTag                        : True
EnableUnauthenticatedSender         : True
EnableSuspiciousSafetyTip           : False

Id                                  : Office365 AntiPhish Default
Enabled                             : True
EnableTargetedUserProtection        : True
EnableMailboxIntelligenceProtection : True
EnableTargetedDomainsProtection     : True
EnableOrganizationDomainsProtection : True
EnableMailboxIntelligence           : True
EnableSimilarUsersSafetyTips        : True
EnableSimilarDomainsSafetyTips      : True
EnableUnusualCharactersSafetyTips   : True
EnableSpoofIntelligence             : True
EnableViaTag                        : True
EnableUnauthenticatedSender         : True
EnableSuspiciousSafetyTip           : False
```

are these false positives?

possibly related: #114

**Comment by luckman212** [comment]
test https://github.com/cammurray/orca/blob/master/Checks/check-ORCA180.ps1#L45

**Comment by rafaelborter** [comment]
Hi @luckman212 

I have the same problem. Microsoft changed a Cmdlet, but did not update the documentation.
EnableAntispoofEnforcement has been renamed to EnableSpoofIntelligence.

After the adjustments via PowerShell, I still get the recommendation from the ORCA report, although the setting has now been set correctly. EnableAntispoofEnforcement should be adapted to EnableSpoofIntelligence in the ORCA-report.

https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3713

**Comment by NehavPandey** [comment]
@luckman212  Can you test with the current release 1.10.6.  and confirm if the issue still persists

**Comment by luckman212** [comment]
thank you @NehavPandey 
Just updated & tested v1.10.6 - For me, it's still reporting this false positive.

![image](https://user-images.githubusercontent.com/1992842/111482027-e583af00-8709-11eb-8620-487f69b1eef1.png)

There is no way to edit the setting on the default Strict policy (https://protection.office.com/presetSecurityPolicies) so there seems to be no way to remove this flag.

![image](https://user-images.githubusercontent.com/1992842/111482336-309dc200-870a-11eb-8225-e78252737742.png)

**Comment by karashah1** [comment]
Hey Luke (@luckman212)

Can you please share a screenshot of the Strict Security Preset policy? 

The PS output confirms that the setting is enabled but need to see what it shows on UI. It will help us confirm if this is a problem within ORCA, product related or something particular to your organization.

**Comment by luckman212** [comment]
@karashah1 There's nothing to really screenshot. No settings are shown, nothing can be modified. 

https://protection.office.com/presetSecurityPolicies

![image](https://user-images.githubusercontent.com/1992842/114728883-7fd91180-9d0d-11eb-8af5-3c2572530274.png)

![image](https://user-images.githubusercontent.com/1992842/114728897-81a2d500-9d0d-11eb-9595-1c9c59f656d1.png)

**Comment by karashah1** [comment]
@luckman212 

Thanks for the response! Let me share the steps to reach the screen we need.

In the above screenshots you shared, after you click 'Edit' > Set some user/group/domain in Step 1 & Step 2 > Click Confirm. The policy should now be enabled.

Visit protection.office.com > Threat Management > Policy > Anti-Phishing
![image](https://user-images.githubusercontent.com/67892508/114824470-8ab1a600-9de2-11eb-99e0-c100f959704d.png)

You should see a 'Strict Preset Security Policy' shows up.
![image](https://user-images.githubusercontent.com/67892508/114824653-d6644f80-9de2-11eb-9abc-db3db5c44168.png)

On clicking the policy a separate panel opens up with all policy details, need a screenshot of that.
![image](https://user-images.githubusercontent.com/67892508/114825246-96ea3300-9de3-11eb-8cf6-c47c1704e0a7.png)

**Comment by luckman212** [comment]
Ok thanks for those steps @karashah1 

Here are the screenshots from my end:

![image](https://user-images.githubusercontent.com/1992842/114884153-892cb180-9dd3-11eb-9b67-7c59dbddb897.png)

![image](https://user-images.githubusercontent.com/1992842/114884528-d4df5b00-9dd3-11eb-9af8-332b76668869.png)

**Comment by cammurray** [comment]
@NehavPandey @karashah1 if the policy is a pre-set policy, we will probably need to ignore it.

**Comment by luckman212** [comment]
@karashah1 @NehavPandey @cammurray Good news—I re-ran ORCA against this problematic tenant this morning, and got a clean result. 🎉 

Version still says 1.10.6...

![image](https://user-images.githubusercontent.com/1992842/115872027-5146ef00-a40f-11eb-96da-5a76d947d489.png)

Something changed?

**Comment by NehavPandey** [comment]
Thanks . Closing the issue
