### ISSUE TITLE
ORCA future

### ISSUE THREAD

**Issue by MisterBendo** [cammurray/orca#128]
I noticed in the Security and Compliance center under Threat Management -> Policy, there is a component called Configuration Analyzer which recommends settings that overlap with recommendations generated in the ORCA reports.  Is this configuration analyzer going replace the ORCA reports?  I notice there hasn't been a new version of ORCA since October.  Is all development now going into the Configuration analyzer?  Of does one not have anything to do with the other?  Put another way, is there any road map for ORCA?

**Comment by luckman212** [comment]
@MisterBendo Thanks for posting that question. I noticed this a couple of weeks ago and was going to ask the same thing. Sure seems like MS is adopting ORCA and baking it into SCC.

**Comment by anthonynz** [comment]
Wouldn't it be grand if you could export the results from the online BPA (configuration analyzer) to CSV.  
In full for a baseline record, and just the recommendations/deviations.

Having the configuration drift analysis exportable with a comparison against the last baseline would be awesome too.

**Comment by cammurray** [comment]
We are actively working on feature parity with config analyser and ORCA. There are no plans to deprecate ORCA today :)

**Comment by anthonynz** [comment]
> We are actively working on feature parity with config analyser and ORCA. There are no plans to deprecate ORCA today :)

Thanks Cam, great to hear we're not losing it.  The tool has been really useful to capture configuration for documentation and reporting.

**Comment by cammurray** [comment]
Closing this out now as it was just a question.
