### ISSUE TITLE
Control values are inconsistent

### ISSUE THREAD

**Issue by jamesgarriss** [cammurray/orca#131]
The control values are inconsistently formatted. Some are like "ORAC-101", others like "101", and others like 101.  We have a downstream process that uses these values, so it would be nice to have them in a consistent format.  I attempted to submit a merge request with consistent values, but I got a 403.

**Comment by cammurray** [comment]
@jamesgarriss Just adding here that there are some negative implications to fixing this, in that if you are using CSV/JSON/Cosmos output and relying on the control ID for matching, then by changing this, you effectively break correlation.

So whilst I admit it's not ideal, fixing it will break stuff & the ID is only intended for a unique identifier for the check/is not exposed outside of raw outputs.
