### ISSUE TITLE
Add SPF check

### ISSUE THREAD

**Issue by jurajsucik** [cammurray/orca#135]
Add check for SPF records, if they are set and if they are set to soft or hard fail. 
MSFT guidance: https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/set-up-spf-in-office-365-to-help-prevent-spoofing?view=o365-worldwide

**Comment by NehavPandey** [comment]
This feature been released in ORCA 2.0 version. Please reopen if issue still persists.
