### ISSUE TITLE
Components to be added

### ISSUE THREAD

**Issue by mparlakyigit** [cammurray/orca#136]
Hi
Components I think should be added
1.Users with No MFA Configured
2.Improper Number of Company/Global Administrators
3.Password Expiration Period is Set
4.Calendar Sharing with External Users Enabled
5.SharePoint External Sharing Enabled.

MFA, MFA,MFA :)

**Comment by cammurray** [comment]
Hey @mparlakyigit 

Thanks for the feedback, ORCA is designed specifically to review MDO components & configuration, and try do that well. We are not intending on creating a full/wholistic security review, but to identify configuration issues within MDO.

For a more holistic security review, I'd suggest using Secure Score.

I'll close this one out but if you discover anything that you feel is critical on the MDO side, do let us know.
