### ISSUE TITLE
New quarantine policies

### ISSUE THREAD

**Issue by ThibaudNSI** [cammurray/orca#138]
Hello,

Microsoft add the feature "quarantine policies" to EOP/Defender for O365.
With this, the "EnableEndUserSpamNotifications" setting is not well detected anymore.
I also think that the Orca report should include checks for these quarantine policies, as well as recommend the type of quarantine policy per anti-spam/anti-phishing action.

Thanks for the efforts! Really useful tool!

**Comment by NehavPandey** [comment]
This feature been released in ORCA 2.0 version. Please reopen if issue still persists.
