### ISSUE TITLE
SafeLink policy not detected when using Preset Security Policies

### ISSUE THREAD

**Issue by angusmclean11** [cammurray/orca#139]
When the tenant is configured to use the Preset Security Policies either Standard or Strict this creates Safe Links policy. When running the Orca Report the section titled "Apply a Safe Links policy to every domain" shows that all domains have no policy applied which is incorrect.

If you create a new Safe Links policy and stop using the Preset Security Policies the Orca Report does show correctly that domains are protected by a policy.

**Comment by NehavPandey** [comment]
This has been fixed in ORCA 2.0 version. Please test and reopen if issue still persists.
