### ISSUE TITLE
non-email domains not to be checked for DKIM

### ISSUE THREAD

**Issue by BrianKnipfel** [cammurray/orca#140]
Some domains are configured that do not send email at all and we get yellow warnings....can these be fixed to not show the warning if no mx records? 

The signing status shows "no configuration" or False and gives a not recommended....

We have some domains that do not send email setup but they show up as failures with yellow warning. IF email is NOT configured/enabled for the domain there is no need to check some setting. Can this be looked at to optimize?

**Comment by ltadi** [comment]
kinda of this topic, but any idea dose this even support anymore tenants? Am getting `ORCA was unable to connect to Exchange Online, or you do not have sufficient permissions to check ORCA related configuration.` no metter what tenant am part of, sooo stressful :(

**Comment by BrianKnipfel** [comment]
Any feedback on this one?

**Comment by cammurray** [comment]
@BrianKnipfel how would you suggest we differentiate here? Any domain configured as an accepted domain is potentially a sending domain. There is no way for us to know you won’t ever send from that domain?

**Comment by BrianKnipfel** [comment]
@cammurray  so remember years ago when we picked what services were on the domain when we set them up?  IE Exchange, Skype and SP?  If we had that indicator still, you'd see that email isn't supposed to be setup and then wouldn't need to check it?  I have some UPN only domains that we have no email on.  Really appreciate the awesome work on this tool as it helps so much to ensure we're adhering to best practices!

**Comment by snehakishore21** [comment]
We have released new version with the required changes. You can test once and let us know if you are still experiencing any issues. Closing this issue for now. Feel free to reopen the issue if issue still persists.

**Comment by BrianKnipfel** [comment]
So I see a false signing setting now but get a "not recommended -5" in red.  I don't want to past our domains here but can send you a screen shot via email

**Comment by BrianKnipfel** [comment]
Thank you! These are now appearing as i was hoping for.  We appreciate your efforts on this stuff!
