### ISSUE TITLE
Does ORCA work at all after 2021?

### ISSUE THREAD

**Issue by ltadi** [cammurray/orca#141]
as title already shows. Am getting this error:
`ORCA was unable to connect to Exchange Online, or you do not have sufficient permissions to check ORCA related configuration.` 
I am GA of tenant but nothing seems to help this issues, modules are all up to date.

**Comment by NehavPandey** [comment]
ORCA is working fine for all other users , it seems to be a localized issue. Can you try connecting to ExchangeOnline from powershell? Please use run commands and let us know the result :
Connect-ExchangeOnline
Connect-IPPSession

**Comment by ltadi** [comment]
Hi, thanks for replay. I did connect first to EO then running `Get-ORCAReport` does promt to connect to EO again so i do it again and it connects to Exchange successfully but when i run `Get-ORCAReport` i get error:

`ORCA was unable to connect to Exchange Online, or you do not have sufficient permissions to check ORCA related configur
ation.
At C:\Program Files\WindowsPowerShell\Modules\ORCA\1.10.6\ORCA.psm1:129 char:9
+         Throw "ORCA was unable to connect to Exchange Online, or you  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ORCA was unable... configuration.:String) [], RuntimeException
    + FullyQualifiedErrorId : ORCA was unable to connect to Exchange Online, or you do not have sufficient permissions
    to check ORCA related configuration.`


Connect-IPPSession gives me also error while runing this command as follow:

`Connect-IPPSession : The term 'Connect-IPPSession' is not recognized as the name of a cmdlet, function, script file, or
 operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try a
gain.
At line:1 char:1
+ Connect-IPPSession
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-IPPSession:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by NehavPandey** [comment]
Can you share the output of following command Get-InstalledModule

**Comment by NehavPandey** [comment]
@ltadi You may get the installed module version using Get-InstalledModule command. The latest version of Exchange online is ExchangeOnlineManagement GA is 2.0.5 and preview is  2.0.6-preview4. Request you to update the version and try again. Let us know if you still face issue.

**Comment by ltadi** [comment]
> @ltadi You may get the installed module version using Get-InstalledModule command. The latest version of ExchangeOnlineManagement GA is 2.0.5 and preview is 2.0.6-preview4. Request you to update the version and try again. Let us know if you still face issue.

thank you so much, i will try to see and troubleshoot this issues and will came back with report

**Comment by NehavPandey** [comment]
Closing since there is no comment.
