### ISSUE TITLE
Enable End-user spam notifications and set the frequency to 3 days

### ISSUE THREAD

**Issue by BrianKnipfel** [cammurray/orca#142]
So we have our policy set to 2 days and lose "points" as we are not following the 3 days..Is there a reason for this?  I'm not sure 1, 2 or 3 days really matters.

![EUSN](https://user-images.githubusercontent.com/58778871/153242131-ba94247f-05cd-428d-bdf8-bec97310b631.png)

**Comment by laklug** [comment]
From my point of view this should only be "Informational" because the count of days is not relevant regarding security. There are many customers who need to react fast if a false positive is detected. Therefore this setting is even set to 1 day often.

**Comment by fabihndlmr** [comment]
@BrianKnipfel Could you please tell me where you have set the value to "2"? Because I think I changed the correct value (https://security.microsoft.com/quarantinePolicies -> Global settings) to "3", but ORCA Report still shows value "1".
Thanks in advance!

**Comment by BrianKnipfel** [comment]
@fabihndlmr  Yes, that is the correct spot...the global we have set to 2.

**Comment by cammurray** [comment]
Probably should be informational, agreed.

The only downside to having a quarantine notification set too frequently is that you end up exposing potential bad mail to the end-user more often. It’s the “junk mail folder” problem, if the mail is extremely accessible to the user, they have a higher chance of considering a legit catch caught in quarantine is a FP, releasing it, and clicking. By sending notifications really frequently to the user, you’re exposing this mail more often for bad judgement. Users need to feel as if messages in quarantine are legitimate catches, and I’m not sure really frequent quarantine notifications is the right way of doing that.


Saying all of that, again, I think that the security risk is probably low enough that we should only be flagging it as informational.

**Comment by BrianKnipfel** [comment]
@cammurray MS is changing this to hourly!
https://techcommunity.microsoft.com/t5/microsoft-defender-for-office/simplifying-the-quarantine-experience-part-two/ba-p/3354687

Anyway, this attribute will need some tweaking again based on that and hate losing points ;)

**Comment by cammurray** [comment]
> @cammurray MS is changing this to hourly! https://techcommunity.microsoft.com/t5/microsoft-defender-for-office/simplifying-the-quarantine-experience-part-two/ba-p/3354687
> 
> Anyway, this attribute will need some tweaking again based on that and hate losing points ;)

To be clear, an hourly option is being introduced. There isn't a recommendation to change to hourly.

But yes, the point is taken - if the point system is based on the security implications of a particular control, I personally don't see why we need to deduct points from the scoring system based on the limited impact. I think we need to ensure that the wording reflects that there is some impact, however.

**Comment by snehakishore21** [comment]
We have released new version with the required changes. You can test once and let us know if you are still experiencing any issues. Closing this issue for now. Feel free to reopen the issue if issue still persists.

**Comment by BrianKnipfel** [comment]
Fixed up now...good to close
