### ISSUE TITLE
SafeLinks Built-In Protection Policy is rated in general - DoNotAllowClickThrough

### ISSUE THREAD

**Issue by laklug** [cammurray/orca#144]
This Built-In Policy is managed by Microsoft and therefore cannot be edited. We have other SafeLinks Policies in Place where DoNotAllowClickThrough is set to true. Nevertheless the Built-In Policy ist rated. This should only be the case if this would be the only policy in place.
![image](https://user-images.githubusercontent.com/99720138/154037287-35ac50c3-3d88-499b-a84e-3c79493625dc.png)

**Comment by NehavPandey** [comment]
This has been fixed in ORCA 2.0 version. Please test and reopen if issue still persists.
