### ISSUE TITLE
EnduserSpamNotifications in CustomPolicy (ORCA 2.0)

### ISSUE THREAD

**Issue by BohrenAn** [cammurray/orca#150]
Hi All,

I am using the ORCA 2.0 PowerShell Module

I think that there is something wrong with the detection of EnduserSpamNotifications in CustomPolicy 
![image](https://user-images.githubusercontent.com/45082822/161730807-1285e88b-143b-4c6b-b838-65cefa3101b6.png)

Get-HostedContentFilterPolicy -Identity "PolicyName" | fl *SpamNotification*
![image](https://user-images.githubusercontent.com/45082822/161730845-cefb4abc-d0b6-4908-bbec-fca87be7d5e2.png)

Microsoft is moving anyway to "Quarantine Policy".
https://blog.icewolf.ch/archive/2021/11/05/exchange-online-quarantine-policy.aspx

Can you please verify?

Regards
Andres

**Comment by snehakishore21** [comment]
@BohrenAn  we have released new version with the required changes. You can test once and let us know if you are still experiencing any issues. Closing this issue for now. Feel free to reopen the issue if issue still persists.

**Comment by BohrenAn** [comment]
@snehakishore21 
Thank's for the Update.
Confirm. The Issue has ben solved with 2.1.
Thank you 😍

**Comment by cammurray** [comment]
Has been confirmed fixed.
