### ISSUE TITLE
Wrong SPF Check

### ISSUE THREAD

**Issue by yhof1** [cammurray/orca#151]
Hi,

We are using Orca Version 2.0
We have many domains and for 2 of them we get SPF "Not Detected" result  even that on Nslookup.io and mxtoolbox we get that our SPF  record is valid (for the orca SPF's check is valid),
for more information could you contact me by email?

Thanks.

**Comment by snehakishore21** [comment]
Can you share more details and screenshots of the SPF records on Nslookup.io and mxtoolbox?
Can you also share your email id, so that we can contact you?

**Comment by NehavPandey** [comment]
@yhof1 Are you still facing the issue?

**Comment by yhof1** [comment]
Yes.

I ran orca again and I still have the same issue.

Regards,
Yoav

**Comment by yhof1** [comment]
Hi,

I think I understand what the issue is:
Those 2 domains managed by both Internal DNS and External DNS (the other domains are not)
We don’t have the SPF record in the internal DNS, only on the external DNS.
Does the Orca process looks for DNS records base on the DNS settings on the machine its runs from? Could you please change it to looks against External DNS like google NS?

Regards,
Yoav

From: Yoav Hoffman
Sent: Wednesday, 8 June 2022 9:40
To: cammurray/orca ***@***.***>; cammurray/orca ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [cammurray/orca] Wrong SPF Check (Issue #151)

Yes.

I ran orca again and I still have the same issue.

Regards,
Yoav

**Comment by yhof1** [comment]
HI,

After configuring the SPF records on the internal DNS as well, its works, but on my opinion, it will be better that you will change the orca function to check it against External DNS (public) and not trust internal DNS records.

Thanks,
Yoav

From: Yoav Hoffman
Sent: Wednesday, 8 June 2022 10:47
To: cammurray/orca ***@***.***>; cammurray/orca ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [cammurray/orca] Wrong SPF Check (Issue #151)

Hi,

I think I understand what the issue is:
Those 2 domains managed by both Internal DNS and External DNS (the other domains are not)
We don’t have the SPF record in the internal DNS, only on the external DNS.
Does the Orca process looks for DNS records base on the DNS settings on the machine its runs from? Could you please change it to looks against External DNS like google NS?

Regards,
Yoav

From: Yoav Hoffman
Sent: Wednesday, 8 June 2022 9:40
To: cammurray/orca ***@***.******@***.***>>; cammurray/orca ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [cammurray/orca] Wrong SPF Check (Issue #151)

Yes.

I ran orca again and I still have the same issue.

Regards,
Yoav
