### ISSUE TITLE
Issue with safelinks policy

### ISSUE THREAD

**Issue by tspring80** [cammurray/orca#154]
Customized Safelinks policy shows as disabled because IsEnabled parameter not exists anymore in cmdlet.
![image](https://user-images.githubusercontent.com/31645674/178954484-237fd7f3-ada7-4fb0-ad2f-f9c0b8e07503.png)

https://github.com/MicrosoftDocs/microsoft-365-docs/issues/8636

Can anyone fix that please? Thanks.

**Comment by snehakishore21** [comment]
As IsEnabled parameter is not available in the cmdlet, now we are required to check the status of the corresponding safe links rule for all the safe links policy. We are updating the value accordingly. We have updated these changes in our latest release. Please check that once and let us know if the issue still persists.

**Comment by tspring80** [comment]
Ok, I see there is a new version available now. I still was use version 2.0.
![image](https://user-images.githubusercontent.com/31645674/178971242-82b24032-0f7a-4aad-a7c6-463d23607585.png)
Thanks.

**Comment by snehakishore21** [comment]
$policyname= "Safe Links Baseline Policy"
$Rule = Get-SafeLinksRule| Where-Object {$_.Name -eq $policyName}
if($($Rule.State) -eq "Enabled")
            {
                 $IsEnabled = $true
          }

Here $policyname is the name of the policy, here it is: Safe Links Baseline Policy
$IsEnabled is checked using the corresponding rule's status for that policy:
Please do check this once, if this is returning true in your case or not?

**Comment by tspring80** [comment]
It don't give back $true. 
But it cannot work like that, because the policyname in my case is "Safe Links Baseline Policy" and the rule name "Safe Links Basline"
But you ask for **$.Name -eq $policyName** and not **$.SafeLinksPolicy -eq $policyName**

**Comment by cammurray** [comment]
Related to #157

**Comment by cammurray** [comment]
Closing this as it is fixed in 2.3 which will be pushed out shortly.
