### ISSUE TITLE
ORCA - Safe Links Tracking Duplicate

### ISSUE THREAD

**Issue by lfuentesisd** [cammurray/orca#159]
Receiving incorrect verdicts for the same policy. Also, seeing the policy twice. Default profile is disabled and TrackClicks set to enabled (True) in this scenario.
![safelinks](https://user-images.githubusercontent.com/99924731/191140533-491021aa-e313-4687-8a0e-64a8b7bb4170.png)

**Comment by amandaw33** [comment]
also seeing this "not recommended" on default policy issue which doesn't match my settings. Didn't have issue when I ran this in Sept.

**Comment by RK-MS** [comment]
We do not see Default policy for Safe links feature, but report still shows Default as an entry.

**Comment by cammurray** [comment]
Dupe of #169 and cause is #177 which i'll fix for 2.3.
