### ISSUE TITLE
Configuration Health Index

### ISSUE THREAD

**Issue by trisdev75** [cammurray/orca#160]
Hello,

I have a question about the configuration health index, I hope you can answer it.
Before June, this indicator was not present. 

How is it calculated? 

In order to make statistics, I would like to calculate it for the months where the indicator was not yet available. 
(We run the ORCA report every month to track the safety of our tenant).

Thanks in advance for your help.

Best Regards,

Tristan.

**Comment by cammurray** [comment]
Hey @trisdev75 

The configuration health index was added back in september 2020 (pull request #110 ) - it's possible you've been running an old version?

The health index for ORCA is intended to be a measured figure based on the estimated security impact that configuration has to your tenant. Each check get's a score and that score is added up to give you the configuration health index.

Closing this for now but feel free to re-open if you have other questions later.

**Comment by trisdev75** [comment]
Thank you for your feedback. 

Indeed, I updated the module only recently, I was using an old version.
