### ISSUE TITLE
Misleading Information & action in Anti-Malware

### ISSUE THREAD

**Issue by ubaystian** [cammurray/orca#163]
### Section - Disable notifying external senders of malware detection

**There it has been written like this:**

> _Notifying external senders about malware detected in email messages could have negative impact. An adversary may use this information to verify effectiveness of malware detection._

**But in the security.microsoft.com has been written like this:**

> _Notify an admin about undelivered messages from external senders_

**Not External sender that will be notified, but our internal admin.**
Thanks for the attention team

**Comment by cammurray** [comment]
This will be deprecated in 2.3.
