### ISSUE TITLE
Safe Links Policy Rules and Safe Attachments Policy Rules show "No Policy Applying" for all domains

### ISSUE THREAD

**Issue by kirilvalev** [cammurray/orca#165]
When applying Strict and Standard policy presets the policy is applied using a selection for "All Recipients". Thus, there is no option to apply the preset policy to specific domains.

I assume, the policy is applied to all domains, when "All Recipients" is selected, however this is not reflected in the ORCA report.

![image](https://user-images.githubusercontent.com/44725404/209157695-44511984-2f90-4cb7-996b-14831414fe7f.png)

ORCA version is 2.1

**Comment by cammurray** [comment]
@kirilvalev Yeh this shouldn't actually be a thing anymore with the built-in policies. I've logged #187 and will probably end up deprecating the "Apply a Safe Links policy to every domain" and the "Apply a Safe Attachments policy to every domain" checks.

**Comment by cammurray** [comment]
226 and 227 to be replaced with #196 to check for holes in the built-in protection, and policies on top (also considering strict/standard presets/custom).

**Comment by cammurray** [comment]
Code checked in and waiting on 2.3 deployment
