### ISSUE TITLE
Configure enhanced filtering on connectors when email path is not direct to EOP - Wrong recommendation?

### ISSUE THREAD

**Issue by eliasmanchon** [cammurray/orca#168]
It appears as improvement recommendation when the MX record is pointed directly at the service. There is not connectors.

**Comment by cammurray** [comment]
Hey @eliasmanchon I can't replicate this, are you able to give me more detail by sending me an email?

**Comment by cammurray** [comment]
Will close until more author reaches out. May be related to #109.
