### ISSUE TITLE
Enable tracking of user clicks in Safe Links Policies - Wrong recommendation

### ISSUE THREAD

**Issue by eliasmanchon** [cammurray/orca#169]
A recommendation appears about TrackClicks in a policy "Default [Default]" that it does not exist.

**Comment by cammurray** [comment]
Hey @eliasmanchon this is due to #177 

In short, there's a check for the org-wide ATP policy to determine if track clicks is on, that's no longer a thing. We will remove the check as part of #177 and get it done for 2.3
