### ISSUE TITLE
Errors after typing "GetORCAReport"

### ISSUE THREAD

**Issue by ToughDBlue** [cammurray/orca#17]
I installed the module fine but every time I type "GetORCAReport" I get the following error:
get-orcareport : The 'get-orcareport' command was found in the module 'ORCA', but the module could not be loaded. For
more information, run 'Import-Module ORCA'.
At line:1 char:1
+ get-orcareport
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (get-orcareport:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

**Comment by cammurray** [comment]
Hi @ToughDBlue 

It sounds like there is an issue autoloading the ORCA module.

Can you run 'Import-Module ORCA'  and show the results?

**Comment by ToughDBlue** [comment]
Hi @cammurray 
Here is my result:
PS C:\Users\RichLusk> import-module orca
import-module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ import-module orca
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by cammurray** [comment]
Hi @ToughDBlue 

We are pushing out 1.4 in the next couple of hours which changes the way that the PSD file is being generated (what tells powershell what files to load for the module). If possible can you please try again once that's pushed out - i'll comment back here to let you know when that's the case.

**Comment by ToughDBlue** [comment]
Hi @cammurray 

Were you able to publish 1.4?  I tried again and it failed.

**Comment by cammurray** [comment]
Hi @ToughDBlue  we had a last minute check in yesterday, so just doing some final testing and then will push it out soon.

**Comment by cammurray** [comment]
Hi @ToughDBlue 

We've just published 1.4 in the PowerShell gallery. Are you able to update and try again? Thanks

**Comment by ToughDBlue** [comment]
Hi @cammurray 
Same problem.  
PS C:\temp\m365\Exchange> Install-Module ORCA -scope currentuser -force
PS C:\temp\m365\Exchange> Get-ORCAReport
Get-ORCAReport : The 'Get-ORCAReport' command was found in the module 'ORCA', but the module could not be loaded. For
more information, run 'Import-Module ORCA'.
At line:1 char:1
+ Get-ORCAReport
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ORCAReport:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

PS C:\temp\m365\Exchange> import-module orca
import-module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ import-module orca
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by cammurray** [comment]
Hi @ToughDBlue 

That's very weird, I can't replicate this issue so it appears to be something with the configuration of the machine. What version OS are you running this under?

Can you provide the output of the following for me:

Get-Module -ListAvailable ORCA | Format-List

and

Get-ExecutionPolicy

**Comment by ToughDBlue** [comment]
Hi @cammurray 
Windows 10 Pro 1909

PS C:\temp\m365\Exchange> Get-Module -ListAvailable ORCA | Format-List


Name              : ORCA
Path              : C:\Users\myname\OneDrive - Company,
                    Inc\Documents\WindowsPowerShell\Modules\ORCA\1.4.5\ORCA.psd1
Description       : Office 365 Advanced Threat Protection Recommended Configuration Analyzer (ORCA)
ModuleType        : Manifest
Version           : 1.4.5
NestedModules     : {}
ExportedFunctions : Get-ORCAReport
ExportedCmdlets   :
ExportedVariables :
ExportedAliases   :

Name              : ORCA
Path              : C:\Users\my name\OneDrive - Company,
                    Inc\Documents\WindowsPowerShell\Modules\ORCA\1.3.2\ORCA.psd1
Description       : Office 365 Advanced Threat Protection Recommended Configuration Analyzer (ORCA)
ModuleType        : Manifest
Version           : 1.3.2
NestedModules     : {}
ExportedFunctions : Get-ORCAReport
ExportedCmdlets   :
ExportedVariables :
ExportedAliases   :

Name              : ORCA
Path              : C:\Users\my name\OneDrive - Company,
                    Inc\Documents\WindowsPowerShell\Modules\ORCA\0.3.2\ORCA.psd1
Description       : Office 365 Advanced Threat Protection Recommended Configuration Analyzer (ORCA)
ModuleType        : Manifest
Version           : 0.3.2
NestedModules     : {}
ExportedFunctions : Get-ORCAReport
ExportedCmdlets   :
ExportedVariables :
ExportedAliases   :

PS C:\temp\m365\Exchange> Get-ExecutionPolicy
RemoteSigned
PS C:\temp\m365\Exchange>

**Comment by cammurray** [comment]
Although it shouldn't, I wonder if your RemoteSigned requirement is conflciting. Can you unblock the files by running:

Unblock-File "C:\Users\myname\OneDrive - Company,
Inc\Documents\WindowsPowerShell\Modules\ORCA\1.4.5\*"
Unblock-File "C:\Users\myname\OneDrive - Company,
Inc\Documents\WindowsPowerShell\Modules\ORCA\1.4.5\Checks*"

I suspect you need to replace "myname" with your name.

**Comment by ToughDBlue** [comment]
I successfully unblocked the files and tried again.  But no go. :(

PS C:\temp\m365\Exchange> Install-Module ORCA -scope currentuser -force
PS C:\temp\m365\Exchange> Get-ORCAReport
Get-ORCAReport : The 'Get-ORCAReport' command was found in the module 'ORCA', but the module could not be loaded. For
more information, run 'Import-Module ORCA'.
At line:1 char:1
+ Get-ORCAReport
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ORCAReport:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

PS C:\temp\m365\Exchange> import-module orca
import-module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ import-module orca
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by cammurray** [comment]
Hi @ToughDBlue 

Two things I would like to narrow down:
1. You're running the module from a OneDrive location, I suspect this is because OneDrive is being set up to redirect your Documents directory.
2. There are spaces in your path which might be causing issues with our dot sourcing of the classes

Easiest way for you to test for us would be to do the following:

1. Go to "C:\Users\myname\OneDrive - Company, Inc\Documents\WindowsPowerShell\Modules\" and move the ORCA folder to c:\temp (or another folder with no spaces in it, and not on OneDrive)
2. Load up PowerShell, ensure that "Get-Module -ListAvailable ORCA" doesn't respond anything - it should be empty now.
3. Run the following command to import the module from the directory:

`Import-Module C:\temp\orca\1.4.5\ORCA.psd1`

4. Now try run Get-ORCAReport

If this works we will try to narrow it down to if it's OneDrive or the spaces causing the problem.

**Comment by ToughDBlue** [comment]
Hi @cammurray 

I followed your instructions and it worked.  I was able to generate the HTML report successfully.  Thank you for your assistance with this.  Please let me know if there are any next steps I can do to help so others don't have the same issue.
