### ISSUE TITLE
Specify Tenant ID?

### ISSUE THREAD

**Issue by bnp-nz** [cammurray/orca#173]
A question please: I may have missed how this can be done, but is there a way to specify the tenant ID when running ORCA? This is for situations where you have been added as a guest to an environment for, say, reviewing configuration and making recommendations.

**Comment by cammurray** [comment]
The Exchange Online PowerShell provides DelegatedOrganization params for connecting which I can pass through.

Happy to put this in to 2.3 because it's pretty easy to implement. I'll need you to test it out for me though as I don't have access to delegated orgs.

**Comment by bnp-nz** [comment]
Absolutely, yes please! I have several delegated org access tests I can perform, and if there's anything further I can do to help please just let me know.

**Comment by cammurray** [comment]
@bnp-nz are you able to try something before we commit this?

Can you first off run Connect-ExchangeOnline -DelegatedOrganization org.onmicrosoft.com

Replacing org.onmicrosoft.com with the organization that you're wanting to run,

Then run Get-ORCAReport -NoConnect

Is the ORCA report provided for the delegate organization? If so, then i'll  commit the changes to push -DelegateOrganization through to the Connect-ExchangeOnline that ORCA runs internally.

**Comment by bnp-nz** [comment]
That worked, thank you indeed, and report was generated as expected (including the "MDO was NOT detected..." status of this org:
![image](https://user-images.githubusercontent.com/69220643/235823835-085783bf-e087-44fb-a9dc-35f01e83a28d.png)

**Comment by cammurray** [comment]
Great @bnp-nz, i've checked int he change to allow you to run Get-ORCAReport -DelegateOrganization directly, instead of the two commands. Expect it to be in for 2.3.
