### ISSUE TITLE
Safe Links settings - Action for unknown or potentially malicious URLs in messages within Microsoft Teams

### ISSUE THREAD

**Issue by DavidTaig** [cammurray/orca#21]
Hi Cam,
Please add for  1.5

**Safe Links settings**
Security feature name: Action for unknown or potentially malicious URLs in messages within Microsoft Teams
Standard or Strict: On

**Comment by cammurray** [comment]
Will be fixed with #157 - we now have to split out IsEnabled to all the workloads.
