### ISSUE TITLE
Preview 2.4 version - number in summary tile "OK" does not match the sum of the same type in "Summary section"

### ISSUE THREAD

**Issue by damozes1** [cammurray/orca#218]
![image](https://github.com/cammurray/orca/assets/45426291/d893b3c9-c06f-4272-95f4-1f1369b58e63)
is 16
adding up Summary section for the same is 15
![image](https://github.com/cammurray/orca/assets/45426291/296fc6e8-f2bb-4374-bcb4-312b7473d9c5)

**Comment by damozes1** [comment]
@cammurray

**Comment by cammurray** [comment]
@damozes1 total counts were not filtering checks that did not complete, where the area counts filtered checks that did not complete - resulting in one result not being represented. Fixed.
