### ISSUE TITLE
Quarantine retention period - HMTL output text needs update

### ISSUE THREAD

**Issue by damozes1** [cammurray/orca#222]
The output for this check still contains old product name in the generated HTML.
"files captured by Advance Threat Protection (ATP) for SharePoint Online, OneDrive for Business, and Microsoft Teams in Office 365."
should be updated to 
"files detected by Microsoft Defender for Office 365 -Safe Attachment for SharePoint, OneDrive, and Microsoft Teams"
here:

check-ORCA106.ps1
$this.Importance="You can view, release, download, delete and report false positive quarantined email messages or files captured by Advance Threat Protection (ATP) for SharePoint Online, OneDrive for Business, and Microsoft Teams in Office 365. Keep messages in the quarantine for 30 days to allow enough time for further investigation. This is the default value and also the maximum."

**Comment by cammurray** [comment]
Fixed across the whole script in #227
