### ISSUE TITLE
Old product name should be replaced with current one in all checks

### ISSUE THREAD

**Issue by damozes1** [cammurray/orca#227]
in couple of Checks "Office 365 ATP" is still used it should be replaced with "Microsoft Defender for Office 365"  
eg.
check-ORCA139.ps1
check-ORCA189.ps1
Checks/check-ORCA115.ps1
Checks/check-ORCA224.ps1
....

**Comment by cammurray** [comment]
@damozes1  yeh there were a tonne of references still - i've killed most of these now, apart from the aka.ms links which i don't think are that big of a deal.
