### ISSUE TITLE
check-ORCA205.ps1 should be improved to check for the presence of default file types enabled in the policies.

### ISSUE THREAD

**Issue by damozes1** [cammurray/orca#228]
check-ORCA205.ps1 should be improved to check for the presence of default file types enabled in the default policies.
Currently if there is 1+ file types we pass. 
consider to check the presence of default blocked values.
![image](https://github.com/cammurray/orca/assets/45426291/f231571b-1854-4320-9b65-585c85eef69b)
https://learn.microsoft.com/en-us/microsoft-365/security/office-365-security/anti-malware-protection-about?view=o365-worldwide#anti-malware-policies

**Comment by cammurray** [comment]
Definitely, put in the vnext bucket though so i can get 2.3 out the door.

**Comment by cammurray** [comment]
Checked in for 2.7
