### ISSUE TITLE
Replace "Whitelisting" with allow listing in all checks

### ISSUE THREAD

**Issue by damozes1** [cammurray/orca#229]
Some checks still uses "Whitelisting" replace it with "Allow listing" or "Override"
eg ETR checks:[orca](https://github.com/cammurray/orca/tree/a4f82885018de072b9ca43ba01c5635f3bd03da6)/[Checks](https://github.com/cammurray/orca/tree/a4f82885018de072b9ca43ba01c5635f3bd03da6/Checks)
/check-ORCA118_3.ps1
or phish policy overrides
Checks/check-ORCA229.ps1

**Comment by cammurray** [comment]
Fixed.
