### ISSUE TITLE
Question: when will the new version (2.3) be available on powershell gallery ?

### ISSUE THREAD

**Issue by ML-NAV** [cammurray/orca#231]
powershell gallery is still listed 2.2 as latested.

**Comment by cammurray** [comment]
Hey @ML-NAV, cheers for reaching out.

Check out the 'ORCAPreview' module if you want the bleeding edge. Will be pushing some more changes to that module today in preperation for a release in next day or so on the main module.

I'll keep this issue up to track the release.

**Comment by ML-NAV** [comment]
Tnx for your response. I see already a bump to 2.5 ;-)
