### ISSUE TITLE
Function Invoke-ORCAConnections connecting Connect-ExchangeOnline

### ISSUE THREAD

**Issue by newwolf** [cammurray/orca#246]
Heyy,

Using your script scheduled for a while but found out it wasn't working anymore.
Dived in you code and discovered you added Connect-ExchangeOnline to Invoke-ORCAConnections.
Could it be possible you check if there is already a active connection with exchangeonline?
like:
try{Get-AcceptedDomain}catch{Connect-ExchangeOnline}

Thanks,
Jos

**Comment by cammurray** [comment]
Hey @newwolf 

Get-ORCAReport intent was to make it as easy as possible for run the report, so we do connect. I'll take your feedback about checking for connection first and see what we can do there - in the interim, you can just put -NoConnect as a param when running Get-ORCAReport and it will skip the connections (you will need an existing connection though).

**Comment by newwolf** [comment]
Thanks, for checking.
Didn't thought about that one, will test it if it's working for us.

**Comment by cammurray** [comment]
Thanks @newwolf closing then, let us know if there's something else.
