### ISSUE TITLE
Update links in report

### ISSUE THREAD

**Issue by hoyty76** [cammurray/orca#248]
The link [Security & Compliance Center - Anti-spam settings](https://aka.ms/orca-antispam-action-antispam) is going to https://protection.office.com/homepage and needs to be updated to https://security.microsoft.com/antispam.

**Comment by hoyty76** [comment]
The link https://aka.ms/orca-atpp-action-antiphishing is going to https://protection.office.com/homepage and needs to be updated to https://security.microsoft.com/antiphishing

**Comment by hoyty76** [comment]
The link https://aka.ms/orca-atpp-action-safelinksv2 is going to https://protection.office.com/homepage and needs to be updated to https://security.microsoft.com/safelinksv2

**Comment by worldsdream** [comment]
It would be nice if the links can be changed. I am having the same problem.

**Comment by ignoramii** [comment]
Upvote.  Really frustrating to figure out which which 'portal' features have moved to after dead end links.

**Comment by cammurray** [comment]
Noted all, thank you for the feedback, will get these fixed.

**Comment by cammurray** [comment]
Checked in to 2.6 in #256

**Comment by worldsdream** [comment]
@cammurray Do you have an ETA for when 2.6 will be released? Thank you.

**Comment by cammurray** [comment]
@worldsdream working on it, technically it's done - and you can download the code from here and run it - but the publishing to the PowerShell gallery is dependant on some code-signing things I need to do internally. Hopefully next few days.

**Comment by cammurray** [comment]
@worldsdream sorry, had some internal issues with code-signing which have now been resolved. Should be able to push changes more easily now. 2.6 is published.
