### ISSUE TITLE
Setup instruction

### ISSUE THREAD

**Issue by amcamillo** [cammurray/orca#258]
The guidance for setup could include details on how to connect and authenticate to ExchangeOnline via Powershell, from the official guide: https://learn.microsoft.com/en-us/powershell/exchange/connect-to-exchange-online-powershell?view=exchange-ps

This command is all we need: Connect-ExchangeOnline -UserPrincipalName <UPN>

**Comment by cammurray** [comment]
Hey @amcamillo, shouldn't need to though, because Get-ORCAReport should connect for you?

**Comment by cammurray** [comment]
Closing as no response.
