### ISSUE TITLE
DNS Server setting

### ISSUE THREAD

**Issue by nicolasbogo** [cammurray/orca#26]
In order to resolve a potential problem in case of a local split DNS configuration. Could you please add a new parameter in the command line (like -DNSName) to be able to select and force a DNS Server instead of using the default server settings.

**Comment by cammurray** [comment]
Hi @nicolasbogo 

I've just checked in code to support a param for alternate dns. It'll be in the next release later this week. For reference:

Usage in Version 1.5:
`Get-ORCAReport -AlternateDNS 10.10.10.10`

Pull request ref #30
