### ISSUE TITLE
Evaluation of non-email domains

### ISSUE THREAD

**Issue by brianberryNZ** [cammurray/orca#261]
The capability exists in O365/EOL to add a domain to O365 and then not configure it for Exchange Services - No DNS records. Following on from that, you are able to set the domain as "Blocked" from sending in EOL. You may do this if you plan to use the domain for applications, but not for other O365 services.
EOL still adds the domain as an Accepted domain, and you cannot remove it.
The ORCA then evaluates accepted domains for email security (spf, DKIM and potentially DMARC). It would be ideal if ORCA checked to see if the domain is set up for Exchange in DNS and if the domain is set to "Blocked" for sending, and then evaluate it accordingly.

**Comment by cammurray** [comment]
Hey @brianberryNZ I don't mind this, but;

- It's common that the domain is pointed at another service which is then pointed to ours.
- You may (send) as a domain, but not (receive) - and in that instance you could have an accepted domain and we should do checks such as sender auth, etc, but you wouldn't have an MX record

Ultimately, I don't know of a good way of automatically determining the use case for the domains based on configuration. Thoughts?

**Comment by brianberryNZ** [comment]
Ultimately, the ORCA Report is a tool for us to use to evaluate the configuration of our tenant. We should each understand the specific configurations we have in place in our tenants. If the report identifies something which could be an issue, and we personally evaluate it and find it to be no problem for us, then we've both done the right thing.
I guess the only additional thing you may identify in your report is the fact that the domain has been configured with "Allow Sending" set to No (SendingFromDomainDisabled True). 
Trying to decide what the admin intends for the domain is a step too far.
