### ISSUE TITLE
The term 'Get-ProtectionAlert' is not recognized

### ISSUE THREAD

**Issue by SamErde** [cammurray/orca#263]
I ran this with the Exchange Online Management 3.3.0 module in PowerShell 7.3.6 and Windows PowerShell 5.1, and got the following error: 

>Get-ProtectionAlert: The term 'Get-ProtectionAlert' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Per the [docs article](https://learn.microsoft.com/en-us/powershell/module/exchange/get-protectionalert) for that cmdlet, "This cmdlet is available only in Security & Compliance PowerShell. For more information, see [Security & Compliance PowerShell](https://learn.microsoft.com/en-us/powershell/exchange/scc-powershell)."

It looks like the SCC module should be listed in the pre-requisites and installation section of the README unless I'm missing that detail somewhere already.

**Comment by SamErde** [comment]
It has been a while since I've used the Security and Compliance module, but it looks like that functionality has been [mostly?] rolled into the Exchange Online Management module along with the Connect-IPPSSession cmdlet.

**Comment by SamErde** [comment]
Will chip away at this as I find time. A search for that cmdlet only shows up one time in the repo: currently [line 644](https://github.com/cammurray/orca/blob/5314cbca09c5ffbe8e78f43df20c8d125a198109/ORCA.psm1#L644) in the Get-ORCACollection function.

**Comment by cammurray** [comment]
Hey @SamErde, we run Get-ProtectionAlert since 2.4 for the purpose of ensuring the default alerts (which can trigger AIR, ZAP, etc) are not disabled. You can add -NoSCC to the Get-ORCAReport in order to bypass these checks.

SCC should be inside the Exchange Online Managemement module though?

Can you run `Get-Command Connect-IPPSSession`?

Do you get any errors (other than the missing command) when running Get-ORCAReport?

**Comment by SamErde** [comment]
I no longer have access to the environment where I experience this, but will continue to use and update if I see it happen elsewhere. Thanks!
