### ISSUE TITLE
Add direct links to settings in order to improve admins changes 

### ISSUE THREAD

**Issue by nicolasbogo** [cammurray/orca#31]
On every control made by ORCA, it would be a good idea to add direct links (or at least an information) to easily find the settings that the administrators have to change in order to retrieve the recommanded settings.
It's a little bit hard for some administrators to find where they have to change settings.

**Comment by cammurray** [comment]
Thanks @nicolasbogo

We will look in to this as part of the 1.6 release

**Comment by cammurray** [comment]
Hi @nicolasbogo we've added deep links in to the pull request #52 for the next release (1.7).
