### ISSUE TITLE
Unified Audit Log False Positive

### ISSUE THREAD

**Issue by jenlg** [cammurray/orca#6]
Our tenant has unified audit log enabled, but orcareport shows "improvement."

**Comment by cammurray** [comment]
Hi @jenlg 

What’s the output of the following command, ran from PowerShell connected to exchange online:

`Get-AdminAuditLogConfig | Select-Object UnifiedAuditLogIngestionEnabled `

**Comment by jenlg** [comment]
It is returning false.

I was under the impression I had the correct settings because at protection.office.com, I do have data visible.

Should I set this setting to true and the OrcaReport will agree logging is enabled?

**Comment by cammurray** [comment]
@jenlg are you getting *exchange* administrative audit information in to the UAL? Changes for instance, to mail flow rules in Exchange Online, to a spam/malware policy, etc - do they appear within the UAL?

**Comment by jenlg** [comment]
Under Search | Activities, I have a "Exchange mailbox activities" section that has user level actions (I can audit "Created mailbox item" and see end user activity.

But I don't see any sections / categories that correspond to the examples you mentioned of Exchange administrative audit info.

**Comment by cammurray** [comment]
Closing. UAL isn't enabled on tenant.
