### ISSUE TITLE
Update Help

### ISSUE THREAD

**Issue by damianscoles** [cammurray/orca#70]
In the Get-Help for Get-ORCAReport the '-Report' parameter is listed in Examples 2 and 3.  This option does not exist in the cmdlet.  Since the help is not updatable nor is there an online version of help ('-online' switch), can the help be updated to show that that '-Report' is not a valid option (removed from Help)?  Can we then add Output to examples as well?  Or take information from the Readme in this GitHub and place it in the Get-Help for the cmdlet?  Thanks.

**Comment by cammurray** [comment]
Definitely a bug, need to fix up the param's help segments now that we've made changes.

I'll get it done before we push out the next release.

**Comment by damianscoles** [comment]
Cam,

No worries, just wasn’t sure the best way to handle this.  Love the module.  You have a lot of fans at the consulting firm where I work as well.  Taking feature requests? 😉

Thanks again for the replies and keep up the good work.


Damian Scoles
Microsoft MVP, Author (PowerShell Books)

**Comment by cammurray** [comment]
Hi @damianscoles thanks very much for the feedback, and yes please keep it coming.

I've just checked in an update to the get-help segment in #73 That'll now be in the ORCAPreview module and will be pushed in to ORCA release module later this week/early next.
