### ISSUE TITLE
Install EXO Remote Session dependency and detect if WinRMRunning

### ISSUE THREAD

**Issue by jingsta** [cammurray/orca#72]
Add ability to detect if dependency (Exchange Online Remote Session) is installed and install it if not. Be sure to prompt user to install prior to doing it. 

you can reference https://raw.githubusercontent.com/jingsta/powershell-scripts/master/Microsoft/O365/O365-SecurityAssessment.ps1 and re-use the function I used. 

Need to also determine if WinRM service is running and if not, enable it. 

$WinRMRunning = (Get-Service 'WinRM').Status
Enable-PSRemoting -Force

**Comment by cammurray** [comment]
We won't override WinRM settings as these are usually restricted based on some kind of security concern.

We do now in preview install ExchangeOnlineManagement in to the CurrentUser scope.
