### ISSUE TITLE
'Invoke-ORCA -PerformVersionCheck $False' Produces Error

### ISSUE THREAD

**Issue by damianscoles** [cammurray/orca#79]
Trying to automate this for another reporting script and when I use the '-PerformVersionCheck $False' parameter, I am getting an error:

05/21/2020 22:11:09 Output - HTML
You cannot call a method on a null-valued expression.
At C:\Users\DScoles\Documents\WindowsPowerShell\Modules\ORCAPreview\1.8.1\Outputs\output-html.ps1:149 char:47
+ ...       <strong>Version $($this.VersionCheck.Version.ToString())</stron ...
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

My guess is that the handling of the no version check is tripping something (I have not delved into it to check).  I am using the 1.8.1 version of the Preview module so hopefully this is the right place to report that.

**Comment by cammurray** [comment]
Hey @damianscoles 

Yeh that would be because the HTML output doesn't check that the versioncheck variable exists. This should be very easy to fix, i'll try get it done today for you.

Cheers

**Comment by cammurray** [comment]
Hi @damianscoles 

This should now be fixed in preview, sorry for the delay.
