### ISSUE TITLE
Application cannot be started..contact the application vendor

### ISSUE THREAD

**Issue by kalyankomara** [cammurray/orca#8]

**Comment by cammurray** [comment]
Hi @kalyankomara 

Are you referring to the error when you try to download the exchange shell from an unsupported browser? If so, it has to do with the application packaging method that's used for this old module and wont appear on the non-chromium edge, for instance..

You can get around this by instead using the preview REST powered Exchange Online Management  module which is available here: https://www.powershellgallery.com/packages/ExchangeOnlineManagement

I'll close this off for now but if you think it's unrelated please re-open.
