### ISSUE TITLE
Get-ORCAReport returns recommendations in odd order

### ISSUE THREAD

**Issue by brianreidc7** [cammurray/orca#80]
It would be great if the order the results are returned in was in line with the policy that is being changed. That is, when you have a recommendation to change a policy in the report and the next recommendation is a different policy, and the n recommendation is back to the first policy. Please can you return the results so that all settings for a single policy appear together.

**Comment by cammurray** [comment]
Hi @brianreidc7 

Thanks for the feedback.

In the next release we are 'modularising' the output generation. This means that whilst our HTML output is currently fixed to this format (presenting by recommendation, not by policy), it will be possible to make a HTML version that groups by policy. The next release won't have what you're asking, but it will enable us to potentially do it in the future, but it will however enable you to get an output in a different format, like CSV (if you choose) which you can then organise in any wya that you need.

**Comment by cammurray** [comment]
@brianreidc7 it seemed logical based on lots of feedback that the expanded config was sorted by the level, so i've gone ahead and done that. in #107 . This code should be checked in now and it should be updated in ORCAPreview (can get via install-module ORCAPreview). Do you mind testing and seeing if this is better?
