### ISSUE TITLE
Invoke-ORCA -CSV Does not produce CSV File

### ISSUE THREAD

**Issue by SkyPi-hash** [cammurray/orca#90]
Running Invoke-ORCA -CSV runs successfully, and spits out the last line of "Generating Report" But the log does not indicate that the CSV is actually created. Further, It does not show up in AppData\Local\Microsoft\ORCA or any other location if -OutputDirectory is specified.

**Comment by cammurray** [comment]
Hi @SkyPi-hash 

Okay, couple of things..

1. What version of ORCA are you running? CSV output is only in the current ORCAPreview module. The released version of ORCA supports HTML, JSON (File) and CosmosDB.
2. Are you intending on getting a CSV output? Run 'Get-ORCAReport' for the normal HTML version
3. If you do intend on running CSV, and you want to try the ORCAPreview module, ensure you check the documentation, because to output CSV would not be `Invoke-ORCA -CSV` it would be `Invoke-ORCA -Output CSV`

**Comment by SkyPi-hash** [comment]
@cammurray  

1) After initially having issues, I did update to the latest ORCA version (I think 1.8 something?). I did perform a Install-module ORCA -force. 
2) I am purposefully attempting to get a CSV version of the report. I am running Invoke-ORCA -Output CSV. The Powershell Output does state it is generation the report, but it does not provide the output "report generated" as when creating a HTML report.

Further, I did inspect the AppData\Local\Microsoft\ORCA path and verified that there are not any CSV files being created.

**Comment by cammurray** [comment]
@SkyPi-hash 

Okay, I suspect you're not running **ORCAPreview** you're running **ORCA**. CSV output is coming in the next release, which means you can only use it in **ORCAPreview** until we've released it.

To see which you're using, can you shoot the result of the following commands;

`Get-Module -ListAvailable ORCA`
`Get-Module -ListAvailable ORCAPreview`

If you can wait, just wait a week or two and you will be able to export CSV using ORCA. If you can't wait, uninstall ORCA and install ORCAPreview.

**Comment by andypituch** [comment]
@cammurray 

I am experiencing this issue with the CSV output, but your response clarifies why it's not working. 

The readme mentions having CSV output and no mention of requiring the preview module so it's a little confusing. I've had no issues exporting the in the HTML or JSON format in a path that I specify... just not CSV.

I'll give preview a try and hope to see this in the release module soon.

**Comment by techeadsrandyr** [comment]
Any ETA on csv export.  Also do you have an ETA on the PowerBI template for the cosmosDB alternative?

**Comment by cammurray** [comment]
Hi @techeadsrandyr we are just having some issues at the moment with the enhanced filtering/skip listing check for the next release, once that's solved we can push the release. Hoping in the next couple of days..

**Comment by cammurray** [comment]
@techeadsrandyr Sorry for the delay, we had some issues with the enhanced filtering check which delayed the release. Good news is that we've just pushed 1.9 out the door which means CSV should be supported now too.

Closing this issue as it's resolved in 1.9.
