### ISSUE TITLE
Return objects don't always have the required properties set

### ISSUE THREAD

**Issue by mpiederiet** [cammurray/orca#92]
In _check-ORCA117.ps1_, the return object doesn't return the "Object" property when no ATP policies are present. E.g.:

According to this, the Object property needs to be present:
 $this.CheckType=[CheckType]::ObjectPropertyValue

**Line 76-79:**
            $ConfigObject = [ORCACheckConfig]::new()
            $ConfigObject.ConfigItem="All"
            $ConfigObject.ConfigData="Enabled False"
            $ConfigObject.SetResult([ORCAConfigLevel]::Standard,"Fail")
**This should be:**
            $ConfigObject = [ORCACheckConfig]::new()
            $ConfigObject.Object ="All"
            $ConfigObject.ConfigItem="IsEnabled"
            $ConfigObject.ConfigData="False"
            $ConfigObject.SetResult([ORCAConfigLevel]::Standard,"Fail")

**Comment by cammurray** [comment]
Hey @mpiederiet  thanks again for a great find - this is fixed next release.
