### ISSUE TITLE
HTML output has several formatting errors

### ISSUE THREAD

**Issue by mpiederiet** [cammurray/orca#93]
The closing tag is not matching the opening tag on several headers in the HTML output.
Some examples:

&lt;**h2** class='card-title'>Office 365 ATP Recommended Configuration Analyzer Report&lt;**/h5**>
-->
&lt;**h2** class='card-title'>Office 365 ATP Recommended Configuration Analyzer Report&lt;**/h2**>

&lt;div class='card-header'>&lt;**h5**>Informational&lt;/**h4**>&lt;/div>
&lt;div class='card-body'>
&lt;**h2**>1&lt;**/h5**>
-->
&lt;div class='card-header'>&lt;<**h5**>Informational</**h5**>&lt;/div>
&lt;div class='card-body'>
&lt;**h2**>1&lt;**/h2**>

&lt;div class='card-header'>&lt;**h5**>Recommendations&lt;/**h4**>&lt;/div>
&lt;div class='card-body'>
&lt;**h2**>13&lt;**/h3**>
-->
&lt;div class='card-header'>&lt;**h5**>Recommendations&lt;/**h5**>&lt;/div>
&lt;div class='card-body'>
&lt;**h2**>13&lt;**/h2**>

&lt;div class='card-header'>&lt;**h5**>OK&lt;/**h4**>&lt;/div>
&lt;div class='card-body'>
&lt;**h2**>41&lt;**/h5**>
-->
&lt;div class='card-header'>&lt;**h5**>OK&lt;/**h5**>&lt;/div>
&lt;div class='card-body'>
&lt;**h2**>41&lt;**/h2**>

**Comment by cammurray** [comment]
@mpiederiet thanks for this, it's been fixed in the next release.
