### ISSUE TITLE
Check for insufficient permissions

### ISSUE THREAD

**Issue by trudolf-msft** [cammurray/orca#99]
In case user has not "Exchange service admin" rights first cmdlet which fails is Get-HostedConnectionFilterPolicy.
I recommend to add a simple check like this:

if(!(Get-Command Get-HostedConnectionFilterPolicy -ErrorAction SilentlyContinue))
{
	Write-Host "Exchange PowerShell module not loaded" -foregroundcolor red
	break
}

**Comment by cammurray** [comment]
Thanks @trudolf-msft  this is a great idea.
